version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    privileged: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://jm_admin:jmS0lut1ons2024!SecureDB@host.docker.internal:5433/jm_solutions
      - JWT_SECRET=jm-solutions-super-secret-key-2024
      - JWT_EXPIRES_IN=7d
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
