version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - jm-solutions-network
    privileged: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://jm_admin:jmS0lut1ons2024!SecureDB@host.docker.internal:5433/jm_solutions
      - JWT_SECRET=jm-solutions-super-secret-key-2024
      - JWT_EXPIRES_IN=7d
      - SCRAPER_SERVICE_URL=http://jm-solutions-lead-scraper:8000
      - IA_SERVICE_URL=http://jm-solutions-ia-service:8001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jm-solutions-network
    privileged: true

networks:
  jm-solutions-network:
    external: true
    name: jm-solutions-network
